import json
import re

from flask import Blueprint, request, send_file
import threading
from flask.json import jsonify
from flask_jwt_extended import (jwt_required)

from py12306.config import Config
from py12306.query.query import Query
from py12306.user.user import User

app = Blueprint('app', __name__)


@app.route('/', methods=['GET', 'POST'])
def index():
    file = Config().WEB_ENTER_HTML_PATH
    result = ''
    with open(file, 'r', encoding='utf-8') as f:
        result = f.read()
        config = {
            'API_BASE_URL': ''  # TODO 自定义 Host
        }
        result = re.sub(r'<script>[\s\S]*?<\/script>', '<script>window.config={}</script>'.format(json.dumps(config)),
                        result)

    return result


@app.route('/app/menus', methods=['GET'])
@jwt_required()
def menus():
    """
    菜单列表
    """
    menus = [
        {"id": 10, "name": "首页", "url": "/", "icon": "fa fa-tachometer-alt"},
        {"id": 20, "name": "用户管理", "url": "/user", "icon": "fa fa-user"},
        {"id": 30, "name": "查询任务", "url": "/query", "icon": "fa fa-infinity"},
        {"id": 40, "name": "实时日志", "url": "/log/realtime", "icon": "fa fa-signature"},
        {"id": 50, "name": "帮助", "url": "/help", "icon": "fa fa-search"}
        ,{"id": 60, "name": "配置中心", "url": "/config", "icon": "fa fa-sliders-h"}
    ]
    return jsonify(menus)


@app.route('/app/actions', methods=['GET'])
@jwt_required()
def actions():
    """
    操作列表
    """
    actions = [
        {"text": "开始抢票" if not __import__('py12306.app', fromlist=['App']).App.TICKETING_STARTED else "抢票运行中", "key": 'start_ticketing', "link": "", "icon": "fa fa-play"},
        {"text": "退出登录", "key": 'logout', "link": "", "icon": "fa fa-sign-out-alt"}
    ]
    return jsonify(actions)

@app.route('/app/ticketing/start', methods=['POST'])
@jwt_required()
def start_ticketing():
    from py12306.app import App
    if not App.TICKETING_THREADS_STARTED:
        App.TICKETING_STARTED = True
        App.TICKETING_THREADS_STARTED = True
        from py12306.user.user import User
        from py12306.query.query import Query
        threading.Thread(target=User.run, daemon=True).start()
        threading.Thread(target=Query.run, daemon=True).start()
    return jsonify({'started': True})

@app.route('/app/config', methods=['GET', 'PUT'])
@jwt_required()
def config_api():
    cfg = Config()
    if request.method == 'GET':
        return jsonify({k: getattr(cfg, k) for k, _ in cfg.envs})
    values = request.get_json(silent=True) or {}
    allowed = {k for k, _ in cfg.envs if k not in cfg.disallow_update_configs}
    for key, value in values.items():
        if key in allowed:
            setattr(cfg, key, value)
    # Persist edits as simple assignments; Config's watcher reloads them.
    try:
        # Rewrite all known assignments as valid Python so nested/multiline
        # values such as USER_ACCOUNTS and QUERY_JOBS remain consistent.
        lines = ['# Generated by py12306 Web 配置中心\n']
        for key, _ in cfg.envs:
            lines.append(key + ' = ' + repr(getattr(cfg, key)) + '\n')
        with open(cfg.CONFIG_FILE, 'w', encoding='utf-8') as f: f.writelines(lines)
    except OSError:
        pass
    return jsonify({'saved': sorted(set(values) & allowed), 'hot_loaded': True})

